/**
 * The `pnpm build:android` gate.
 *
 * Resolves the Android SDK and a JDK without depending on any shell
 * environment, regenerates android/local.properties, and runs the Gradle
 * wrapper with org.gradle.java.home pinned to the resolved JDK. This is what
 * makes the gate work in a fresh shell and in a fresh git worktree, on this
 * Windows host and on the macOS machine used at closeout.
 *
 * Usage: node scripts/build-android.js [gradleTask]   (default: assembleDebug)
 * Env:   RN_ARCHS   comma-separated ABIs (default: arm64-v8a)
 */
'use strict';

const {existsSync, writeFileSync} = require('fs');
const {homedir} = require('os');
const path = require('path');
const {spawnSync} = require('child_process');

const REPO_ROOT = path.resolve(__dirname, '..');
const ANDROID_DIR = path.join(REPO_ROOT, 'android');

function firstExistingDir(candidates) {
  for (const candidate of candidates) {
    if (candidate && existsSync(candidate)) {
      return candidate;
    }
  }
  return null;
}

function resolveAndroidSdkDir() {
  const localAppData = process.env.LOCALAPPDATA;
  return firstExistingDir([
    process.env.ANDROID_HOME,
    process.env.ANDROID_SDK_ROOT,
    localAppData ? path.join(localAppData, 'Android', 'Sdk') : null,
    path.join(homedir(), 'AppData', 'Local', 'Android', 'Sdk'),
    path.join(homedir(), 'Library', 'Android', 'sdk'),
    path.join(homedir(), 'Android', 'Sdk'),
  ]);
}

function resolveJdkDir() {
  return firstExistingDir([
    process.env.JAVA_HOME,
    'C:\\Program Files\\Android\\Android Studio\\jbr',
    '/Applications/Android Studio.app/Contents/jbr/Contents/Home',
    path.join(
      homedir(),
      'Applications',
      'Android Studio.app',
      'Contents',
      'jbr',
      'Contents',
      'Home',
    ),
    '/opt/android-studio/jbr',
  ]);
}

function writeLocalProperties(sdkDir) {
  const file = path.join(ANDROID_DIR, 'local.properties');
  const body = [
    '# Generated by scripts/build-android.js on every build.',
    '# Do not commit and do not edit by hand.',
    `sdk.dir=${sdkDir.replace(/\\/g, '/')}`,
    '',
  ].join('\n');
  writeFileSync(file, body, 'utf8');
  return file;
}

function main() {
  const task = process.argv[2] || 'assembleDebug';
  const archs = process.env.RN_ARCHS || 'arm64-v8a';

  const sdkDir = resolveAndroidSdkDir();
  if (!sdkDir) {
    console.error(
      'Android SDK not found. Set ANDROID_HOME to your SDK directory.',
    );
    process.exit(1);
  }

  const jdkDir = resolveJdkDir();
  if (!jdkDir) {
    console.error(
      'No JDK found. Set JAVA_HOME, or install Android Studio so its bundled JBR is available.',
    );
    process.exit(1);
  }

  console.log(`Android SDK: ${sdkDir}`);
  console.log(`JDK:         ${jdkDir}`);
  console.log(`Gradle task: ${task} (${archs})`);
  writeLocalProperties(sdkDir);

  const isWindows = process.platform === 'win32';
  const wrapper = path.join(ANDROID_DIR, isWindows ? 'gradlew.bat' : 'gradlew');
  const gradleArgs = [
    task,
    `-Dorg.gradle.java.home=${jdkDir}`,
    `-PreactNativeArchitectures=${archs}`,
    '--console=plain',
  ];

  const result = spawnSync(
    isWindows ? 'cmd.exe' : wrapper,
    isWindows ? ['/c', wrapper, ...gradleArgs] : gradleArgs,
    {
      cwd: ANDROID_DIR,
      stdio: 'inherit',
      env: {
        ...process.env,
        JAVA_HOME: jdkDir,
        ANDROID_HOME: sdkDir,
        ANDROID_SDK_ROOT: sdkDir,
      },
    },
  );

  if (result.error) {
    console.error(result.error.message);
    process.exit(1);
  }
  process.exit(result.status === null ? 1 : result.status);
}

module.exports = {
  resolveAndroidSdkDir,
  resolveJdkDir,
  writeLocalProperties,
};

if (require.main === module) {
  main();
}
