import {context} from '@reatom/core';
import {i18n} from '@lingui/core';

import {bootstrapApp} from '../src/app/appEntry';
import {detach} from '../src/app/detach';
import {localeOverride} from '../src/app/locale.model';
import {mockRadio} from '../src/radio/radio.native.mock';
import {renderApp} from '../jest/renderApp';
import {setMockScenario} from '../src/mock/mock.scenario';
import {NativeRadioCallError, createRadioNative} from '../src/radio/radio.native';

jest.useFakeTimers({doNotFake: ['queueMicrotask']});

type Listener = (state: string) => void;

function fakeAppState() {
  const listeners: Listener[] = [];
  return {
    host: {
      addEventListener(_type: 'change', handler: Listener) {
        listeners.push(handler);
        return {
          remove() {
            listeners.splice(listeners.indexOf(handler), 1);
          },
        };
      },
    },
    listeners,
  };
}

const bootHost = () => ({
  systemLocale: 'ru-RU',
  appState: fakeAppState().host,
  devMenu: {addMenuItem: () => {}},
});

beforeEach(() => {
  context.reset();
  setMockScenario('happy');
  mockRadio.reset({scenario: 'happy'});
});

/**
 * Section 13 says nothing throws, and `invoke`/`invokeVoid` make that true for
 * the Turbo Module call itself. These tests cover the gap that is left over:
 * the promises bootstrap starts and does not await. A rejection there is
 * reported by React Native as `Uncaught (in promise, id: N)` -- a crash report
 * generated by the app's own error handling, not by a real failure.
 */
describe('detach — a rejection is a returned value', () => {
  it('returns the rejection reason instead of rejecting', async () => {
    const cause = new TypeError('undefined is not a function');
    await expect(detach(Promise.reject(cause))).resolves.toBe(cause);
  });

  it('carries a resolved value through untouched', async () => {
    await expect(detach(Promise.resolve('ru'))).resolves.toBe('ru');
  });

  it('wraps a non-Error rejection so callers always get an Error value', async () => {
    // React Native's own `AccessibilityInfo.isReduceMotionEnabled()` rejects
    // with `null` on Android, so "the reason is an Error" cannot be assumed.
    const result = await detach(Promise.reject(null));
    expect(result).toBeInstanceOf(Error);
  });
});

describe('RadioNative — resolving the module is part of the guarded call', () => {
  it('returns a call error when the resolver itself throws', async () => {
    const radio = createRadioNative(() => {
      throw new TypeError('undefined is not a function');
    });

    await expect(radio.getAppLocale()).resolves.toBeInstanceOf(NativeRadioCallError);
    await expect(radio.start()).resolves.toBeInstanceOf(NativeRadioCallError);
    await expect(radio.getState()).resolves.toBeInstanceOf(NativeRadioCallError);
  });

  it('returns a call error from subscribe when the resolver throws', () => {
    const radio = createRadioNative(() => {
      throw new TypeError('undefined is not a function');
    });

    expect(radio.subscribe(() => {})).toBeInstanceOf(NativeRadioCallError);
  });
});

describe('bootstrap — a JS bundle newer than the installed native binary', () => {
  /**
   * The proven device condition: `getAppLocale`/`setAppLocale` are `undefined`
   * on the Turbo Module while every older method is still a function, because
   * the installed binary was built before the language picker landed. That is
   * a normal state during development and must cost the user nothing.
   */
  const withoutLocaleMethods = (body: () => Promise<void>) => async () => {
    const stale = mockRadio as unknown as Record<string, unknown>;
    const getter = stale.getAppLocale;
    const setter = stale.setAppLocale;
    delete stale.getAppLocale;
    delete stale.setAppLocale;
    try {
      await body();
    } finally {
      stale.getAppLocale = getter;
      stale.setAppLocale = setter;
    }
  };

  it(
    'settles without a rejection and keeps the system locale',
    withoutLocaleMethods(async () => {
      const boot = bootstrapApp(bootHost());

      await expect(boot.ready).resolves.toEqual([]);
      expect(i18n.locale).toBe('ru');
      expect(localeOverride()).toBe(null);
      boot.teardown();
    }),
  );

  it(
    'still settles when the picker writes to the missing method',
    withoutLocaleMethods(async () => {
      const boot = bootstrapApp(bootHost());
      await boot.ready;

      await expect(localeOverride.select('en')).resolves.toBeInstanceOf(Error);
      expect(i18n.locale).toBe('en');
      boot.teardown();
    }),
  );
});

describe('bootstrap — a rejection that no native guard can prevent', () => {
  /**
   * `wrap()` rejects with an `AbortError` when the Reatom context is reset
   * while it is in flight -- which is what a Fast Refresh does, and what every
   * test in this repository does in `beforeEach`. The call it wrapped had
   * already returned its failure as a value, so no amount of guarding inside
   * `radio.native.ts` prevents this one: bootstrap has to absorb it.
   */
  it('resolves rather than rejecting when the context resets in flight', async () => {
    const boot = bootstrapApp(bootHost());
    context.reset();

    const failures = await boot.ready;
    expect(failures.every(failure => failure instanceof Error)).toBe(true);
    boot.teardown();
  });

  it('absorbs a lifecycle transition that rejects the same way', async () => {
    const appState = fakeAppState();
    const boot = bootstrapApp({
      systemLocale: 'ru-RU',
      appState: appState.host,
      devMenu: {addMenuItem: () => {}},
    });
    await boot.ready;

    appState.listeners[0]('active');
    context.reset();
    for (let tick = 0; tick < 20; tick += 1) await Promise.resolve();

    boot.teardown();
  });
});

describe('first-launch routing — the other promise bootstrap does not await', () => {
  /**
   * `platform.gateway.ts` already says it in a comment: "`resolveInitialRoute`
   * is the only thing that ever leaves `route()` at `null`, so a rejection here
   * is a permanently blank app". The gateway guards its own bodies, but the
   * guard sits below `flatMap` in one method and below `wrap()` in every one of
   * them, so `App`'s mount effect has to absorb the rejection too.
   */
  it('renders rather than rejecting when the gateway throws', async () => {
    const app = await renderApp({
      gateway: {
        hasOnboardingPermissions: async () => {
          throw new TypeError('undefined is not a function');
        },
      },
    });

    expect(app.texts().join('')).not.toBe('');
    app.unmount();
  });
});
